### PR TITLE
Rearch

### PR DESCRIPTION
**Pull request by djsutherland**
`noarch` is breaking AppVeyor builds on python 3.5, similar to https://github.com/conda-forge/six-feedstock/issues/9: see https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.17229/job/skbt63vjhsne77ud#L21.

This undoes it.

@conda-forge/core, all AppVeyor py3.5 builds will be broken until this merges. :|  The noarch build also might need to be manually pulled or something so the 3.5 build of this can even be made?

### CODE REVIEW

**Comment by jakirkham** [comment]
I guess that gives us a chicken or the egg problem. IOW how do we release the fix if this won't build to the aforementioned issue. Sounds like we have to pull the noarch packages first.

**Comment by jakirkham** [comment]
As another thought, it might be worth updating `conda` earlier on in staged-recipes. We do the same thing in the feedstocks, which is probably why they have yet to be affected.

**Comment by jakirkham** [comment]
Also as an FYI the dependency chain looks like this `idna` -> `requests` -> `conda`.

cc @isuruf

**Comment by djsutherland** [comment]
Oh, I see: the feedstocks update `conda` from `defaults` before even adding the `conda-forge` channel. If `staged-recipes` did that too then everything should be fine, except for conda-forge users with old `conda` versions. (Not sure how many of those there are.)

**Review by isuruf — APPROVED** [review]
Maybe we should leave a comment in `meta.yaml`'s `build` section as a reminder.

**Comment by jschueller** [comment]
could https://github.com/conda-forge/staged-recipes/pull/4061 fix your issue? I'd prefer not to go back.

**Comment by djsutherland** [comment]
It will probably fix the staged-recipes issue. Any conda-forge user out there with an old conda may have a hard time updating, though.

**Comment by jschueller** [comment]
Is it reasonably old to say we dont support that, or ?

**Comment by isuruf** [comment]
conda-forge/staged-recipes#4061 is failing

**Comment by jakirkham** [comment]
Went to go redeploy the pinning bot. Unfortunately it seems that `idna` is a blocker for that too. How do we feel about moving this PR forward?

**Comment by jschueller** [comment]
ok I dont want this to be blocking for others

**Pull request merged**
